### PR TITLE
Create fake RSSI from TRSS when former not present

### PR DESCRIPTION
**Pull request by ajjjjjjjj**
Create fake RSSI from TRSS when former not present.

Fixes: #412

### CODE REVIEW

**Comment by ajjjjjjjj** [comment]
@Snekovo, can you test on this build?

**Comment by Snekovo** [comment]
> @Snekovo, can you test on this build?

Yes, I'm happy to test

**Comment by Snekovo** [comment]
> > @Snekovo, can you test on this build?
> 
> Yes, I'm happy to test

I compiled and flashing afhds2a-fake-rssi version.
RX signal indicator on LCD is not present but if I move away it starts flashing.
Alarm signal notifies connection and disconnection of RX On/Off signal previously it did not do this.
Telemetry no longer shows no-data.
Telemetry value A3 still does not work in logical switches.
I attach actual screenshots.

01_flashing_signal_RX
02_flashing_signal_RX
03_telemetry
04_telemetry_screen
05_logical_switch
06_spec_func

**Comment by ajjjjjjjj** [comment]
Seems like problem is somewhere else. Can you edit L03 condition and see when "L03" becomes bold while editnig value, or change condition to see if it ever latches?

**Comment by Snekovo** [comment]
> Seems like problem is somewhere else. Can you edit L03 condition and see when "L03" becomes bold while editing value, or change condition to see if it ever latches?

Incrase decrase voltage A3 or A1 conditions L03 and se3" will not turn on when adjusting the value.

The condition works fine on the original FS-iA6b/FSiA4B receiver.

**Comment by Snekovo** [comment]
> Seems like problem is somewhere else. Can you edit L03 condition and see when "L03" becomes bold while editing value, or change condition to see if it ever latches?
> 
> I have tested it locally using RxBt sensor and it works as expected.

**Sorry, A3 A1 telemetry works, L03 function responds according to condition :)**
I had to start a new model though, removing the addition of sensors was not enough.

Thank you very much for the great work

**Comment by ajjjjjjjj** [comment]
Ok, closing, because the issue was not related to fix.

**Comment by Snekovo** [comment]
> > Seems like problem is somewhere else. Can you edit L03 condition and see when "L03" becomes bold while editing value, or change condition to see if it ever latches?
> > I have tested it locally using RxBt sensor and it works as expected.
> 
> **Sorry, A3 A1 telemetry works, L03 function responds according to condition :)** I had to start a new model though, removing the addition of sensors was not enough.
> 
> Thank you very much for the great work


one anomaly
logical switch "L03" does not work delay parameter

if I set the value to 0-2.0
then the alarm works

if I set my favourite value to >2.0, for example 5.0, then L03 stops working again

**Comment by Snekovo** [comment]
> Ok, can you provide some of TRSSI values from your telemetry on short and long distances?

Flysky FS-iA65 TRRS 30m 190, 1m 230, not-signal 60
CROSSOVER FR7012-A2 TRRS 30m 220, 1m 230, not-signal 90

TRSS behaves strangely and FR7012-A2 has a small parkfly range of about 400m

**Comment by ajjjjjjjj** [comment]
Can you try on recent change to see if value better matches RSSI and there are no issues?
I also plan to define guard it because it is a weird case that telemetry enabled receiver is not returning RSSI and to prevent any side effects for other users.

**Comment by Snekovo** [comment]
> Can you try on recent change to see if value better matches RSSI and there are no issues?
> I also plan to define guard it because it is a weird case that telemetry enabled receiver is not returning RSSI and to prevent any side effects for other users.

**I'll try the change in a week, I'm on vacation.**

Today I still managed to fly about 6 times for 12 minutes. 
Telemetry keeps beeping a low signal it's annoying.
I finally turned off the RSSI watch in the model settings, but then it warns again when I turn on the transmitter.

The A3 telemetry itself works perfectly fine as long as the delay is 2.0 or less.

**Comment by Snekovo** [comment]
> > > Seems like problem is somewhere else. Can you edit L03 condition and see when "L03" becomes bold while editing value, or change condition to see if it ever latches?
> > > I have tested it locally using RxBt sensor and it works as expected.
> > 
> > 
> > **Sorry, A3 A1 telemetry works, L03 function responds according to condition :)** I had to start a new model though, removing the addition of sensors was not enough.
> > Thank you very much for the great work
> 
> one anomaly logical switch "L03" does not work delay parameter
> 
> if I set the value to 0-2.0 then the alarm works
> 
> if I set my favourite value to >2.0, for example 5.0, then L03 stops working again


after returning from vacation I can confirm that I have tested the values up to 10 and the "delay" function is already working correctly

**Comment by Snekovo** [comment]
> Can you try on recent change to see if value better matches RSSI and there are no issues? I also plan to define guard it because it is a weird case that telemetry enabled receiver is not returning RSSI and to prevent any side effects for other users.

I flight for two days, I confirm that better matches RSSI
I set the low alarm to 28 and the critical alarm to 25.

Measured for a receiver (CROSSOVER Telemetry RX FR7012-A2 (AFHDS 2A)) 1 meter above the ground

The low alarm value when the tiger hasn't started yet.
100m 60 
150m 40
200m 28

Signal failure is correctly indicated by a beep and a "No Data" message.

Great work, thank you very much

**Comment by ajjjjjjjj** [comment]
@Snekovo do you, by any chance, have access to EdgeTX radio and can confirm the same behaviour (NO DATA)?

**Comment by Snekovo** [comment]
> @Snekovo do you, by any chance, have access to EdgeTX radio and can confirm the same behaviour (NO DATA)?

We have a colleague in the club with a Radiomaster transmitter equipped with EdgeTX, I will try

**Pull request merged**
