### PR TITLE
Fixed bulk eeprom read.

### LINKED ISSUE #253: Save/Restore EEPROM.BIN to PC does not work
Connecting radio to PC and manually selecting USB-detect auto gives a connection to PC (stroage mode).

One can then copy EEPROM.BIN to PC.

If one tries to restore the EEPROM.BIN (linux: shell command), the file (seems) copied, the radio disconnects immediate, but the it reports an EEProm storage error (or sometimes EEprom full).

### PR DESCRIPTION
**Pull request by ajjjjjjjj**
- Fixed bulk eeprom read.
- Added proper eeprom write wait.
Closes #253

### CODE REVIEW

**Comment by wimalopaan** [comment]
Ok, will test

**Review by wimalopaan — COMMENTED** [review]
Looks good to me

**Review by wimalopaan — APPROVED** [review]
Works

**Comment by ajjjjjjjj** [comment]
Thanks

**Pull request merged**
