### PR TITLE
ELRS menu: (do not) use maxlen for STRING

### PR DESCRIPTION
**Pull request by ajjjjjjjj**
ELRS menu: use maxlen for STRING.
Analyzing crossfire `device.lua` and `elrsV3.lua` this may be how it should be implemented.

You may be interested @wimalopaan

### CODE REVIEW

**Comment by wimalopaan** [comment]
I tested accidentially with a maxlen == 0 and the menu did not show any string chars and misbehaves in the sense, that the first char of the next line gets modified.

Then I sent a maxlen==8. If selecting if highlights the field in its total length and let me edit the char. If I press return, the whole filed gets highlighted again as expected but then up/down does not work anymore. I have to press cancel !? Looks like a minor bug.

**Comment by wimalopaan** [comment]
I did not dig far into the code changes: did you take into account that maxlen is optional?

**Comment by wimalopaan** [comment]
LGTM now

**Comment by ajjjjjjjj** [comment]
> I did not dig far into the code changes: did you take into account that maxlen is optional?

No, but is it?

**Comment by ajjjjjjjj** [comment]
Seems only to be set if loaded string length is > 0. Which makes sense. Also using it as described in my previous message describes how the remaining part of string acts as unit.

**Pull request merged**
