### PR TITLE
CRSF optional STRING and FLOAT support

### PR DESCRIPTION
**Pull request by ajjjjjjjj**
FLOAT:
- [x] extend Param struct,
- [x] display,
- [x] load,
~~- [ ] edit - not sure if needed,~~
- [x] save,

Added `CRSF_EXTENDED_TYPES` define.

### CODE REVIEW

**Comment by wimalopaan** [comment]
I think this requires some additional memory (flash and RAM). I therefore would suggest to make that a compiletime-option (maybe default-on).

**Comment by wimalopaan** [comment]
Well, thats really not that much, but I think when developing a new feature that is seldom used, there should be an option. 

In german: "Kleinvieh macht auch Mist" ;-)

**Comment by ajjjjjjjj** [comment]
Absolutely, that's why it is not included yet.

**Comment by ajjjjjjjj** [comment]
Added `CRSF_EXTENDED_TYPES` define for `STRING` and `FLOAT`. Disabled by default.

**Comment by wimalopaan** [comment]
Great work!!!

**Pull request merged**
