### PR TITLE
Aux serial S-Port mirror

### PR DESCRIPTION
**Pull request by ajjjjjjjj**
- Aux serial S-Port mirror
- Aux serial backports

### CODE REVIEW

**Comment by ajjjjjjjj** [comment]
Debug toggles properly, mirror not tested yet.

**Comment by marianomd** [comment]
Is the output expected to be inverted? Nice renaming backport.

**Comment by ajjjjjjjj** [comment]
I belive so. This is still 1:1 to OpenTX.

**Comment by marianomd** [comment]
The thing is all other radios have a hardware inverter on the s-port. So we have two options. 1) Stay compatible with other radios, for that we should invert the serial output like we do to communicate with CRSF modules, or 2) Output uninverted CRSF (leave the code as it is right now).
This depends a lot on what uses will this have. If this is going to be used with this [Android app](https://github.com/CrazyDude1994/android-taranis-smartport-telemetry) we can leave it uninverted, and users will avoid having to add a hardware inverter before the HC-05 or similar module.

**Review by marianomd — APPROVED** [review]

**Comment by ajjjjjjjj** [comment]
How i understand it: CRSF data goes by S.Port no matter if this is inverted in STM32 periphal or external hardware inverter.
Aux serial is standard serial and must be determined be e2e testing if this works or must be inverted using USART_InvPinCmd when in mirror mode.

**Comment by marianomd** [comment]
I've been thinking about the inversion, and don't find the 
situation where it would be needed . If you connect it to PC or Android through Bluetooth module, you will need it uninverted. The only hardware I imagine that would expect the signal to be inverted is some proprietary head tracker or similar. (Don't know of any)

**Comment by wimalopaan** [comment]
Is there also SBUS-Input possible?

**Comment by ajjjjjjjj** [comment]
It's possible if there will be someone willing to contribute that functionality to the project.

**Pull request merged**
