### PR TITLE
ELRS menu: additional data types support

### PR DESCRIPTION
**Pull request by ajjjjjjjj**
INT8, UINT16, INT16, STRING support.

FLOAT support will be back in another PR, when needed.

### CODE REVIEW

**Comment by ajjjjjjjj** [comment]
Yes, it all depends on existing use case that it needs. If you have device that relays on it, i'll add it.

**Comment by wimalopaan** [comment]
> Yes, it all depends on existing use case that it needs. If you have device that rely on it, i'll add it.

Oh yes, that would be real cool, because the `elrsV3.lua` of EdgeTx can't do that.

**Comment by wimalopaan** [comment]
Just saw that you already worked on that ... congratulations!!!

**Comment by ajjjjjjjj** [comment]
Can you paste here sample CRSF STRING packet to test?

**Comment by wimalopaan** [comment]
> Can you paste here sample CRSF STRING packet to test?

Sure, I hope I'll find the time tomorrow.

**Comment by wimalopaan** [comment]
Here is a LA trace:

la1

The parameter name and value are displayed correctls, but if I click OK, then a complete reload starts.

(As you can see the name and value (both null terminated) are followed by the (optional) "units" field (whatever units means for string-type parameter).

**Comment by wimalopaan** [comment]
Here is another trace where the string parameter="Name", Value="bla" as before but the parameter has parent 0.

But clicking on the parameter triggers a reload instead an edit-box.

**Comment by wimalopaan** [comment]
Missed the image ...

la2

**Comment by wimalopaan** [comment]
> Thanks, it was not tested yet, so there are issues for sure.

No problem, take your time ;-)

**Comment by ajjjjjjjj** [comment]
Try now. I have tested edit mode behaviour but not checked if returned data is correct.

**Comment by wimalopaan** [comment]
Added an issue for this: https://github.com/crsf-wg/crsf/issues/21

**Comment by ajjjjjjjj** [comment]
Good point, I think yes, as it is with the name and params list for TEXT_SELECTION type.

**Comment by ajjjjjjjj** [comment]
There is another issue. There should be ability to make string longer - what is maximum allowed length of editable STRING? I can assume 10 for now, because that whats fits BW screen comfortably.

**Comment by wimalopaan** [comment]
> There is another issue. There should be ability to make string longer - what is maximum allowed length of editable STRING? I can assume 10 for now, because that whats fits BW screen comfortably.

Absolutely.
I made another issue for that: https://github.com/crsf-wg/crsf/issues/22

**Comment by wimalopaan** [comment]
I think 10 +1 is ok for the now.

**Comment by wimalopaan** [comment]
Looks good to me.

**Comment by wimalopaan** [comment]
Still works ;-) 
But why did you remove FLOAT support?

**Comment by ajjjjjjjj** [comment]
Because of space constraints, I may leave it as define guarded.
I'm still working on reducing size (unify int8/16 handling).

**Comment by wimalopaan** [comment]
> Because of space constraints, I may leave it as define guarded. I'm still working on reducing size (unify int8/16 handling).

Yes, memory is tight on that radio.
Maybe you can leave the FLOAT support as a compile-time option?

**Comment by ajjjjjjjj** [comment]
FLOAT support will be back in another PR, when needed

**Pull request merged**
