### PR TITLE
USB Serial modes

### LINKED ISSUE #415: Is it possible to have USB-Serial for Telemetry mirror?
For recent version, the remote can interface via USB port in 2-mode, storage mode and Joytick mode. Is it possible to add the third mode as USB Serial?
Normally STM32 USB can be configured as USB-Serial so we can use telemetry mirror to PC easily and neat without additional wiring.

### PR DESCRIPTION
**Pull request by ajjjjjjjj**
Enables USB Serial mode forced to Telemetry mirror, or debug output in DEBUG builds.

Closes #415

### CODE REVIEW

**Comment by wimalopaan** [comment]
I get this one:

/home/lmeier/Projekte/openix6/opentx.wmgit/radio/src/translations.cpp:436:34: error: 'TR_USB_TELEMETRY' was not declared in this scope; did you mean 'STR_USB_TELEMETRY'?
436 | const char STR_USB_TELEMETRY[] = TR_USB_TELEMETRY;
|                                  ^~~~~~~~~~~~~~~~
|                                  STR_USB_TELEMETRY
make[3]: *** [radio/src/CMakeFiles/firmware.dir/build.make:832: radio/src/CMakeFiles/firmware.dir/translations.cpp.o] Fehler 1

**Comment by ajjjjjjjj** [comment]
It is only for EN at the moment.

**Comment by ajjjjjjjj** [comment]
@wimalopaan it should compile now without errors.

**Comment by wimalopaan** [comment]
Oh yes, it does! Thank you. 
But it will take some days until I can test it (if needed).
BTW: does the telemetry-mirror also work for ELRS?

**Comment by ajjjjjjjj** [comment]
Take your time :) 
Telemetry mirror works for both - any CRSF/ELRS device and internal AFHDS2A.

**Pull request merged**
